<?php
require_once dirname(__DIR__) . '/includes/install/install_web_gate.php';
require_once dirname(__DIR__) . '/includes/install/install_web_preflight.php';
require_once dirname(__DIR__) . '/includes/install/install_web_schema.php';
require_once dirname(__DIR__) . '/includes/install/install_web_bootstrap.php';
require_once dirname(__DIR__) . '/includes/install/install_web_admin_publish.php';
require_once dirname(__DIR__) . '/includes/install/install_web_finalize.php';

header('Cache-Control: no-store, no-cache, must-revalidate'); header('Pragma: no-cache');
header('X-Frame-Options: DENY'); header('X-Content-Type-Options: nosniff'); header('Referrer-Policy: no-referrer');
header("Content-Security-Policy: default-src 'none'; style-src 'self'; img-src 'self'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'");

$repo=realpath(dirname(__DIR__));
$locked=$repo===false || is_file($repo.'/install.lock') || is_file($repo.'/.install.lock.pending');
$resolution=$repo===false?array('path'=>null):dqs_install_web_runtime_resolve($repo);
$runtime=$repo===false?null:dqs_install_web_runtime_validate($resolution['path'],$repo,$_SERVER['DOCUMENT_ROOT']??null,true);
$lockTarget=($repo!==false&&$runtime!==null)?dqs_install_web_admin_publish_target($repo,$runtime):null;
$locked=$locked||($lockTarget!==null&&(is_file($lockTarget.'/install.lock')||is_file($lockTarget.'/.install.lock.pending')));
$gate=$runtime===null?null:dqs_install_web_read_gate($runtime);
session_name('DQS_INSTALLER_SESSION'); $https=!empty($_SERVER['HTTPS'])&&strtolower((string)$_SERVER['HTTPS'])!=='off';
session_set_cookie_params(array('lifetime'=>0,'path'=>'/install/','secure'=>$https,'httponly'=>true,'samesite'=>'Strict')); session_start(); $now=time();
$authenticated=!empty($_SESSION['dqs_installer_authenticated']);
$expired=$authenticated&&(($now-(int)($_SESSION['last_activity']??0)>600)||$now>(int)($_SESSION['absolute_expires']??0));
if($expired){if($runtime!==null){dqs_install_web_admin_publish_cleanup($_SESSION['admin_publish_file_private_path']??null,$runtime);dqs_install_web_bootstrap_cleanup($_SESSION['bootstrap_file_private_path']??null,$runtime);dqs_install_web_preflight_cleanup($_SESSION['db_connection_file_private_path']??null,$runtime);}$_SESSION=array();$authenticated=false;}
if(!isset($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));
$method=$_SERVER['REQUEST_METHOD']??'GET';$action=$method==='POST'?($_POST['action']??''):'';
$allowedActions=array('login','logout','db_preflight','schema_dry_run','schema_apply','bootstrap_dry_run','bootstrap_apply','admin_publish_dry_run','admin_publish_apply','finalize_dry_run','finalize_apply');
$requestBlocked=($method!=='GET'&&$method!=='POST')||($method==='POST'&&!in_array($action,$allowedActions,true));
if($method==='GET'&&(isset($_GET['secret'])||isset($_GET['action'])))$requestBlocked=true;
$csrfValid=$method!=='POST'||(isset($_POST['csrf'])&&is_string($_POST['csrf'])&&hash_equals($_SESSION['csrf'],$_POST['csrf']));
if($method==='POST'&&$action==='logout'&&$csrfValid){if($runtime!==null){dqs_install_web_admin_publish_cleanup($_SESSION['admin_publish_file_private_path']??null,$runtime);dqs_install_web_bootstrap_cleanup($_SESSION['bootstrap_file_private_path']??null,$runtime);dqs_install_web_preflight_cleanup($_SESSION['db_connection_file_private_path']??null,$runtime);}$_SESSION=array();if(ini_get('session.use_cookies')){$p=session_get_cookie_params();setcookie(session_name(),'',time()-42000,$p['path'],$p['domain'],$p['secure'],$p['httponly']);}session_destroy();header('Location: ./',true,303);exit;}
$gateFingerprintMatches=$authenticated&&is_array($gate)&&isset($_SESSION['gate_session_fingerprint'])&&is_string($_SESSION['gate_session_fingerprint'])&&hash_equals($_SESSION['gate_session_fingerprint'],dqs_install_web_gate_session_fingerprint($gate));
if($authenticated&&!$gateFingerprintMatches){if($runtime!==null){dqs_install_web_admin_publish_cleanup($_SESSION['admin_publish_file_private_path']??null,$runtime);dqs_install_web_bootstrap_cleanup($_SESSION['bootstrap_file_private_path']??null,$runtime);dqs_install_web_preflight_cleanup($_SESSION['db_connection_file_private_path']??null,$runtime);}$_SESSION=array('csrf'=>bin2hex(random_bytes(32)));$authenticated=false;}
$baseAvailable=!$locked&&!$requestBlocked&&$csrfValid&&is_array($gate);
if($method==='POST'&&$action==='login'&&$baseAvailable&&!$authenticated){if(dqs_install_web_consume_secret($runtime,$_POST['secret']??null)){$gateAfterConsume=dqs_install_web_read_gate($runtime);if(is_array($gateAfterConsume)){session_regenerate_id(true);$_SESSION=array('dqs_installer_authenticated'=>true,'authenticated_at'=>$now,'last_activity'=>$now,'absolute_expires'=>$now+1800,'csrf'=>bin2hex(random_bytes(32)),'gate_session_fingerprint'=>dqs_install_web_gate_session_fingerprint($gateAfterConsume));header('Location: ./',true,303);exit;}}$gate=dqs_install_web_read_gate($runtime);}
$authenticated=!empty($_SESSION['dqs_installer_authenticated']);$available=$baseAvailable&&is_array($gate)&&dqs_install_web_gate_available($gate,$authenticated);
if(!$available&&$authenticated&&$runtime!==null){dqs_install_web_admin_publish_cleanup($_SESSION['admin_publish_file_private_path']??null,$runtime);dqs_install_web_bootstrap_cleanup($_SESSION['bootstrap_file_private_path']??null,$runtime);dqs_install_web_preflight_cleanup($_SESSION['db_connection_file_private_path']??null,$runtime);$_SESSION=array();$authenticated=false;}
if($authenticated&&$available)$_SESSION['last_activity']=$now;
function dqs_install_schema_session_clear(){foreach(array('schema_dry_run_result','schema_dry_run_status','schema_dry_run_at_utc','schema_dry_run_fingerprint','schema_apply_result','schema_apply_status','schema_apply_at_utc','schema_include_default_content')as$key)unset($_SESSION[$key]);}
function dqs_install_finalize_session_clear(){foreach(array('finalize_dry_run_result','finalize_dry_run_status','finalize_dry_run_at_utc','finalize_dry_run_fingerprint','finalize_apply_result','finalize_apply_status','finalize_apply_at_utc')as$key)unset($_SESSION[$key]);}
function dqs_install_admin_publish_session_clear($runtime){dqs_install_finalize_session_clear();dqs_install_web_admin_publish_cleanup($_SESSION['admin_publish_file_private_path']??null,$runtime);foreach(array('admin_publish_file_private_path','admin_publish_dry_run_result','admin_publish_dry_run_status','admin_publish_dry_run_at_utc','admin_publish_dry_run_fingerprint','admin_publish_apply_result','admin_publish_apply_status','admin_publish_apply_at_utc','admin_publish_slug')as$key)unset($_SESSION[$key]);}
function dqs_install_bootstrap_session_clear($runtime){dqs_install_admin_publish_session_clear($runtime);dqs_install_web_bootstrap_cleanup($_SESSION['bootstrap_file_private_path']??null,$runtime);foreach(array('bootstrap_file_private_path','bootstrap_dry_run_result','bootstrap_dry_run_status','bootstrap_dry_run_at_utc','bootstrap_dry_run_fingerprint','bootstrap_apply_result','bootstrap_apply_status','bootstrap_apply_at_utc')as$key)unset($_SESSION[$key]);}
if($method==='POST'&&$action==='db_preflight'&&$available&&$authenticated){dqs_install_bootstrap_session_clear($runtime);dqs_install_web_preflight_cleanup($_SESSION['db_connection_file_private_path']??null,$runtime);unset($_SESSION['db_connection_file_private_path']);dqs_install_schema_session_clear();list($safeResult,$privatePath)=dqs_install_web_preflight_run($runtime,array('host'=>$_POST['db_host']??null,'dbname'=>$_POST['db_name']??null,'username'=>$_POST['db_user']??null,'password'=>$_POST['db_password']??null));$_SESSION['db_preflight_result']=$safeResult;$_SESSION['db_preflight_status']=$safeResult['status'];$_SESSION['db_preflight_at_utc']=gmdate('c');if($privatePath!==null)$_SESSION['db_connection_file_private_path']=$privatePath;$_SESSION['csrf']=bin2hex(random_bytes(32));header('Location: ./',true,303);exit;}
if($method==='POST'&&in_array($action,array('schema_dry_run','schema_apply'),true)&&$available&&$authenticated){
 $preflightOk=in_array($_SESSION['db_preflight_status']??null,array('OK','WARN'),true);$connection=dqs_install_web_schema_connection($_SESSION['db_connection_file_private_path']??null,$runtime);
 if($action==='schema_dry_run'){
  $include=isset($_POST['include_default_content'])&&$_POST['include_default_content']==='1';
  if(isset($_SESSION['schema_apply_status'])&&in_array($_SESSION['schema_apply_status'],array('OK','WARN'),true))$safe=dqs_install_web_schema_blocked('Schema ya fue aplicado; no se permite repetir la operación.');
  elseif(!$preflightOk||$connection===null)$safe=dqs_install_web_schema_blocked('Schema requiere un preflight vigente y su conexión privada válida.');
  else{$safe=dqs_install_web_schema_run_dry($connection,$include);$_SESSION['schema_include_default_content']=$include;if(in_array($safe['status'],array('OK','WARN'),true)){$at=gmdate('c');$_SESSION['schema_dry_run_at_utc']=$at;$_SESSION['schema_dry_run_fingerprint']=dqs_install_web_schema_fingerprint($connection,$include,$at);}}
  $_SESSION['schema_dry_run_result']=$safe;$_SESSION['schema_dry_run_status']=$safe['status'];
	 }else{
  $include=($_SESSION['schema_include_default_content']??null)===true;$dryOk=in_array($_SESSION['schema_dry_run_status']??null,array('OK','WARN'),true);$fingerprintOk=$connection!==null&&dqs_install_web_schema_fingerprint_valid($_SESSION['schema_dry_run_fingerprint']??null,$connection,$include);
  if(isset($_SESSION['schema_apply_status'])&&in_array($_SESSION['schema_apply_status'],array('OK','WARN'),true))$safe=dqs_install_web_schema_blocked('Schema ya fue aplicado; no se permite repetir la operación.');
  elseif(!$preflightOk||$connection===null||!$dryOk||!$fingerprintOk)$safe=dqs_install_web_schema_blocked('La autorización de dry-run ya no coincide con las entradas actuales.');
  elseif(($_POST['confirm_schema_apply']??null)!=='1'||($_POST['confirmation_phrase']??null)!=='INSTALAR SCHEMA')$safe=dqs_install_web_schema_blocked('Apply requiere el checkbox y la frase exacta de confirmación.');
  else { dqs_install_bootstrap_session_clear($runtime); $safe=dqs_install_web_schema_run_apply($connection,$include); }
  $_SESSION['schema_apply_result']=$safe;$_SESSION['schema_apply_status']=$safe['status'];$_SESSION['schema_apply_at_utc']=gmdate('c');
 }
 $_SESSION['csrf']=bin2hex(random_bytes(32));header('Location: ./',true,303);exit;
}
if($method==='POST'&&in_array($action,array('bootstrap_dry_run','bootstrap_apply'),true)&&$available&&$authenticated){
 $connection=dqs_install_web_schema_connection($_SESSION['db_connection_file_private_path']??null,$runtime);$preflightOk=in_array($_SESSION['db_preflight_status']??null,array('OK','WARN'),true);$schemaOk=in_array($_SESSION['schema_apply_status']??null,array('OK','WARN'),true);$already=in_array($_SESSION['bootstrap_apply_status']??null,array('OK','WARN'),true);
 if($action==='bootstrap_dry_run'){
  dqs_install_web_bootstrap_cleanup($_SESSION['bootstrap_file_private_path']??null,$runtime);foreach(array('bootstrap_file_private_path','bootstrap_dry_run_fingerprint','bootstrap_dry_run_at_utc')as$key)unset($_SESSION[$key]);
  $data=dqs_install_web_bootstrap_validate($_POST);
  if($already)$safe=dqs_install_web_bootstrap_blocked('Bootstrap ya fue aplicado; no se permite repetir la operación.');
  elseif(!$preflightOk||!$schemaOk||$connection===null)$safe=dqs_install_web_bootstrap_blocked('Bootstrap requiere preflight y schema apply vigentes.');
  elseif($data===null)$safe=dqs_install_web_bootstrap_blocked('Los campos de bootstrap no cumplen el template o sus longitudes.');
  else{$bootstrap=dqs_install_web_bootstrap_create($runtime,$connection,$data);unset($data);if($bootstrap===null)$safe=dqs_install_web_bootstrap_blocked('No fue posible crear el archivo privado de bootstrap.');else{$safe=dqs_install_web_bootstrap_run('dry-run',$connection,$bootstrap);$_SESSION['bootstrap_file_private_path']=$bootstrap;if(in_array($safe['status'],array('OK','WARN'),true)){$at=gmdate('c');$_SESSION['bootstrap_dry_run_at_utc']=$at;$_SESSION['bootstrap_dry_run_fingerprint']=dqs_install_web_bootstrap_fingerprint($connection,$bootstrap,$at);}}}
  $_SESSION['bootstrap_dry_run_result']=$safe;$_SESSION['bootstrap_dry_run_status']=$safe['status'];
 }else{
  $bootstrap=dqs_install_web_bootstrap_path($_SESSION['bootstrap_file_private_path']??null,$runtime,$connection);$dryOk=in_array($_SESSION['bootstrap_dry_run_status']??null,array('OK','WARN'),true);$at=$_SESSION['bootstrap_dry_run_at_utc']??null;$fingerprintOk=$bootstrap!==null&&is_string($at)&&isset($_SESSION['bootstrap_dry_run_fingerprint'])&&hash_equals($_SESSION['bootstrap_dry_run_fingerprint'],dqs_install_web_bootstrap_fingerprint($connection,$bootstrap,$at));
  if($already)$safe=dqs_install_web_bootstrap_blocked('Bootstrap ya fue aplicado; no se permite repetir la operación.');elseif(!$preflightOk||!$schemaOk||$connection===null||!$dryOk||!$fingerprintOk)$safe=dqs_install_web_bootstrap_blocked('La autorización de bootstrap dry-run ya no coincide con las entradas actuales.');elseif(($_POST['confirm_bootstrap_apply']??null)!=='1'||($_POST['bootstrap_confirmation_phrase']??null)!=='CREAR BOOTSTRAP')$safe=dqs_install_web_bootstrap_blocked('Apply requiere el checkbox y la frase exacta CREAR BOOTSTRAP.');else { dqs_install_admin_publish_session_clear($runtime); $safe=dqs_install_web_bootstrap_run('apply',$connection,$bootstrap); }
  $_SESSION['bootstrap_apply_result']=$safe;$_SESSION['bootstrap_apply_status']=$safe['status'];$_SESSION['bootstrap_apply_at_utc']=gmdate('c');
 }
 $_SESSION['csrf']=bin2hex(random_bytes(32));header('Location: ./',true,303);exit;
}
if($method==='POST'&&in_array($action,array('admin_publish_dry_run','admin_publish_apply'),true)&&$available&&$authenticated){
 $connection=dqs_install_web_schema_connection($_SESSION['db_connection_file_private_path']??null,$runtime);$preflightOk=in_array($_SESSION['db_preflight_status']??null,array('OK','WARN'),true);$schemaOk=in_array($_SESSION['schema_apply_status']??null,array('OK','WARN'),true);$bootstrapOk=in_array($_SESSION['bootstrap_apply_status']??null,array('OK','WARN'),true);$already=in_array($_SESSION['admin_publish_apply_status']??null,array('OK','WARN'),true);$template=dqs_install_web_admin_publish_template($repo);$target=dqs_install_web_admin_publish_target($repo,$runtime);
 if($action==='admin_publish_dry_run'){
  if(!$already)dqs_install_admin_publish_session_clear($runtime);
  if($already)$safe=dqs_install_web_admin_publish_blocked('Admin publish ya fue completado; no se permite repetir la operación.');
  elseif(!$preflightOk||!$schemaOk||!$bootstrapOk||$connection===null)$safe=dqs_install_web_admin_publish_blocked('Admin publish requiere preflight, Schema apply y Bootstrap apply vigentes.');
  elseif($template===null)$safe=dqs_install_web_admin_publish_blocked('La policy requiere exactamente un template admin permitido.');
  elseif($target===null)$safe=dqs_install_web_admin_publish_blocked('No hay un destino de publicación permitido y seguro.');
  else{$slug=dqs_install_web_admin_publish_slug($target);$config=$slug===null?null:dqs_install_web_admin_publish_create($runtime,$connection,$slug);if($config===null)$safe=dqs_install_web_admin_publish_blocked('No fue posible preparar el input privado de Admin publish.');else{$safe=dqs_install_web_admin_publish_run('dry-run',$connection,$template,$target,$config,$slug);$_SESSION['admin_publish_file_private_path']=$config;$_SESSION['admin_publish_slug']=$slug;if(in_array($safe['status'],array('OK','WARN'),true)){$at=gmdate('c');$_SESSION['admin_publish_dry_run_at_utc']=$at;$_SESSION['admin_publish_dry_run_fingerprint']=dqs_install_web_admin_publish_fingerprint($connection,$config,$template,$target,$slug,$at);}}}
  $_SESSION['admin_publish_dry_run_result']=$safe;$_SESSION['admin_publish_dry_run_status']=$safe['status'];
 }else{
  $config=dqs_install_web_admin_publish_path($_SESSION['admin_publish_file_private_path']??null,$runtime,$connection);$slug=$_SESSION['admin_publish_slug']??null;$at=$_SESSION['admin_publish_dry_run_at_utc']??null;$dryOk=in_array($_SESSION['admin_publish_dry_run_status']??null,array('OK','WARN'),true);$fingerprintOk=$config!==null&&$template!==null&&$target!==null&&is_string($slug)&&is_string($at)&&isset($_SESSION['admin_publish_dry_run_fingerprint'])&&hash_equals($_SESSION['admin_publish_dry_run_fingerprint'],dqs_install_web_admin_publish_fingerprint($connection,$config,$template,$target,$slug,$at));
  if($already)$safe=dqs_install_web_admin_publish_blocked('Admin publish ya fue completado; no se permite repetir la operación.');elseif(!$preflightOk||!$schemaOk||!$bootstrapOk||$connection===null||!$dryOk||!$fingerprintOk)$safe=dqs_install_web_admin_publish_blocked('La autorización de Admin publish dry-run ya no coincide con la policy actual.');elseif(($_POST['confirm_admin_publish_apply']??null)!=='1'||($_POST['admin_publish_confirmation_phrase']??null)!=='PUBLICAR ADMIN')$safe=dqs_install_web_admin_publish_blocked('Apply requiere el checkbox y la frase exacta PUBLICAR ADMIN.');else $safe=dqs_install_web_admin_publish_run('apply',$connection,$template,$target,$config,$slug);
  $_SESSION['admin_publish_apply_result']=$safe;$_SESSION['admin_publish_apply_status']=$safe['status'];$_SESSION['admin_publish_apply_at_utc']=gmdate('c');
 }
 $_SESSION['csrf']=bin2hex(random_bytes(32));header('Location: ./',true,303);exit;
}
if($method==='POST'&&in_array($action,array('finalize_dry_run','finalize_apply'),true)&&$available&&$authenticated){
 $preflightOk=in_array($_SESSION['db_preflight_status']??null,array('OK','WARN'),true);$schemaOk=in_array($_SESSION['schema_apply_status']??null,array('OK','WARN'),true);$bootstrapOk=in_array($_SESSION['bootstrap_apply_status']??null,array('OK','WARN'),true);$adminOk=in_array($_SESSION['admin_publish_apply_status']??null,array('OK','WARN'),true);$already=in_array($_SESSION['finalize_apply_status']??null,array('OK','WARN'),true);$inputs=dqs_install_web_finalize_inputs($repo,$runtime,$_SESSION['db_connection_file_private_path']??null,$_SESSION['admin_publish_slug']??null);$adminAt=$_SESSION['admin_publish_apply_at_utc']??null;
 if($action==='finalize_dry_run'){
  dqs_install_finalize_session_clear();
  if($already)$safe=dqs_install_web_finalize_blocked('Finalize ya fue aplicado; no se permite repetir la operación.');elseif(!$preflightOk||!$schemaOk||!$bootstrapOk||!$adminOk||$inputs===null||!is_string($adminAt))$safe=dqs_install_web_finalize_blocked('Finalize requiere Preflight, Schema, Bootstrap y Admin publish vigentes, además de la carpeta publicada.');else{$safe=dqs_install_web_finalize_run('dry-run',$inputs);if(in_array($safe['status'],array('OK','WARN'),true)){$at=gmdate('c');$_SESSION['finalize_dry_run_at_utc']=$at;$_SESSION['finalize_dry_run_fingerprint']=dqs_install_web_finalize_fingerprint($inputs,$at,$adminAt);}}
  $_SESSION['finalize_dry_run_result']=$safe;$_SESSION['finalize_dry_run_status']=$safe['status'];
 }else{
  $at=$_SESSION['finalize_dry_run_at_utc']??null;$dryOk=in_array($_SESSION['finalize_dry_run_status']??null,array('OK','WARN'),true);$currentFingerprint=$inputs===null?null:dqs_install_web_finalize_fingerprint($inputs,$at,$adminAt);$fingerprintOk=is_string($currentFingerprint)&&isset($_SESSION['finalize_dry_run_fingerprint'])&&hash_equals($_SESSION['finalize_dry_run_fingerprint'],$currentFingerprint);
  if($already)$safe=dqs_install_web_finalize_blocked('Finalize ya fue aplicado; no se permite repetir la operación.');elseif(!$preflightOk||!$schemaOk||!$bootstrapOk||!$adminOk||$inputs===null||!$dryOk||!$fingerprintOk)$safe=dqs_install_web_finalize_blocked('La autorización de Finalize dry-run ya no coincide con el estado validado actual.');elseif(($_POST['confirm_finalize_apply']??null)!=='1'||($_POST['finalize_confirmation_phrase']??null)!=='FINALIZAR INSTALACION')$safe=dqs_install_web_finalize_blocked('Apply requiere el checkbox y la frase exacta FINALIZAR INSTALACION.');else $safe=dqs_install_web_finalize_run('apply',$inputs);
  $_SESSION['finalize_apply_result']=$safe;$_SESSION['finalize_apply_status']=$safe['status'];$_SESSION['finalize_apply_at_utc']=gmdate('c');
 }
 $_SESSION['csrf']=bin2hex(random_bytes(32));
 // Preserve this response so the successful apply can be rendered once, despite the newly created lock.
 if($action==='finalize_apply'&&in_array($safe['status'],array('OK','WARN'),true)){http_response_code(200);$available=true;$locked=false;}else{header('Location: ./',true,303);exit;}
}
if(!$available)http_response_code(403);
function dqs_install_h($value){return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function dqs_install_render_result($title,$result){if(!is_array($result))return;?><section class="result <?=dqs_install_h(strtolower($result['status']))?>"><h2><?=dqs_install_h($title)?>: <?=dqs_install_h($result['status'])?></h2><dl class="metrics"><div><dt>Exit code</dt><dd><?=dqs_install_h($result['exit_code']===null?'—':$result['exit_code'])?></dd></div><div><dt>Duración</dt><dd><?=dqs_install_h($result['duration_ms'])?> ms</dd></div><?php foreach($result['summary']as$key=>$value):?><div><dt><?=dqs_install_h(str_replace('_',' ',$key))?></dt><dd><?=dqs_install_h($value)?></dd></div><?php endforeach;?></dl><ul class="result-checks"><?php foreach($result['checks']as$check):?><li><b><?=dqs_install_h($check['status'])?></b> <code><?=dqs_install_h($check['id'])?></code><p><?=dqs_install_h($check['message'])?></p></li><?php endforeach;?></ul><?php if(!empty($result['errors'])):?><div class="safe-diagnostic"><h3>Diagnóstico seguro</h3><ul><?php foreach($result['errors']as$error):?><li><?=dqs_install_h($error)?></li><?php endforeach;?></ul></div><?php endif;?></section><?php }
$dbResult=$authenticated&&is_array($_SESSION['db_preflight_result']??null)?$_SESSION['db_preflight_result']:null;$preflightStatus=is_array($dbResult)?$dbResult['status']:null;$schemaDry=$authenticated&&is_array($_SESSION['schema_dry_run_result']??null)?$_SESSION['schema_dry_run_result']:null;$schemaApply=$authenticated&&is_array($_SESSION['schema_apply_result']??null)?$_SESSION['schema_apply_result']:null;$schemaStatus=in_array($_SESSION['schema_apply_status']??null,array('OK','WARN'),true)?$_SESSION['schema_apply_status']:(in_array($_SESSION['schema_dry_run_status']??null,array('OK','WARN'),true)?'active':null);$schemaReady=in_array($preflightStatus,array('OK','WARN'),true)&&dqs_install_web_schema_connection($_SESSION['db_connection_file_private_path']??null,$runtime)!==null;$applyReady=$schemaReady&&in_array($_SESSION['schema_dry_run_status']??null,array('OK','WARN'),true)&&!in_array($_SESSION['schema_apply_status']??null,array('OK','WARN'),true);$bootstrapReady=$schemaReady&&in_array($_SESSION['schema_apply_status']??null,array('OK','WARN'),true);$bootstrapDry=$_SESSION['bootstrap_dry_run_result']??null;$bootstrapApply=$_SESSION['bootstrap_apply_result']??null;$bootstrapApplyReady=$bootstrapReady&&in_array($_SESSION['bootstrap_dry_run_status']??null,array('OK','WARN'),true)&&!in_array($_SESSION['bootstrap_apply_status']??null,array('OK','WARN'),true);$adminPublishReady=$bootstrapReady&&in_array($_SESSION['bootstrap_apply_status']??null,array('OK','WARN'),true);$adminPublishDry=$_SESSION['admin_publish_dry_run_result']??null;$adminPublishApply=$_SESSION['admin_publish_apply_result']??null;$adminPublishApplyReady=$adminPublishReady&&in_array($_SESSION['admin_publish_dry_run_status']??null,array('OK','WARN'),true)&&!in_array($_SESSION['admin_publish_apply_status']??null,array('OK','WARN'),true);$finalizeReady=$adminPublishReady&&in_array($_SESSION['admin_publish_apply_status']??null,array('OK','WARN'),true)&&dqs_install_web_finalize_inputs($repo,$runtime,$_SESSION['db_connection_file_private_path']??null,$_SESSION['admin_publish_slug']??null)!==null&&!in_array($_SESSION['finalize_apply_status']??null,array('OK','WARN'),true);$finalizeDry=$_SESSION['finalize_dry_run_result']??null;$finalizeApply=$_SESSION['finalize_apply_result']??null;$finalizeApplyReady=$finalizeReady&&in_array($_SESSION['finalize_dry_run_status']??null,array('OK','WARN'),true);$finalizedResponse=$authenticated&&in_array($_SESSION['finalize_apply_status']??null,array('OK','WARN'),true)&&is_array($finalizeApply);
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Instalador DQS</title><link rel="stylesheet" href="assets/install.css"></head><body><main class="panel"><header><p class="eyebrow">UNI-049.8</p><h1>Instalador DQS</h1></header>
<?php if(!$available):?><section class="notice blocked"><h2>Instalador no disponible</h2><p>El acceso está bloqueado. Contacte al operador autorizado.</p></section><?php elseif(!$authenticated):?><section><h2>Acceso temporal</h2><p>Ingrese el secreto one-time proporcionado por el operador.</p><form method="post" autocomplete="off"><input type="hidden" name="action" value="login"><input type="hidden" name="csrf" value="<?=dqs_install_h($_SESSION['csrf'])?>"><label for="secret">Secreto de acceso</label><input id="secret" name="secret" type="password" required maxlength="512" autocomplete="off"><button type="submit">Continuar</button></form></section><?php else:?>
<?php if($finalizedResponse):?>
<section class="notice"><h2>Cierre OK</h2><p><strong>Instalación finalizada. Se creó install.lock. Al refrescar o volver a abrir /install/, el instalador quedará bloqueado.</strong></p><?php if(isset($_SESSION['admin_publish_slug'])):?><p class="admin-slug">Admin slug: <code><?=dqs_install_h($_SESSION['admin_publish_slug'])?></code></p><?php endif;?></section>
<?php dqs_install_render_result('Finalize apply',$finalizeApply);?>
<section><h2>Controles</h2><ul class="checks"><li>install.lock creado <b>OK</b></li><li>Instalador cerrado <b>OK</b></li></ul></section>
<?php else:?>
<section class="notice"><strong>Finalize controlado / UNI-049.8</strong><p>Finalize reutiliza el CLI validado y solo se habilita después de Admin publish apply.</p></section>
<ol class="steps"><?php foreach(array('Gate','DB / Preflight','Schema','Bootstrap','Admin publish','Finalize','Cierre')as$i=>$step){if($i===0){$class='ok';$label='OK';}elseif($i===1){$class=$preflightStatus?strtolower($preflightStatus):'active';$label=$preflightStatus?:'Paso activo';}elseif($i===2){$class=$schemaStatus?(strtolower($schemaStatus)==='active'?'active':strtolower($schemaStatus)):($schemaReady?'active':'future');$label=$schemaStatus?:($schemaReady?'Paso activo':'Requiere preflight OK/WARN');}elseif($i===3){$bs=$_SESSION['bootstrap_apply_status']??null;$class=$bs?strtolower($bs):($bootstrapReady?'active':'future');$label=$bs?:($bootstrapReady?'Paso activo':'Requiere Schema apply OK/WARN');}elseif($i===4){$ap=$_SESSION['admin_publish_apply_status']??null;$class=$ap?strtolower($ap):($adminPublishReady?'active':'future');$label=$ap?:($adminPublishReady?'Paso activo':'Requiere Bootstrap apply OK/WARN');}elseif($i===5){$fz=$_SESSION['finalize_apply_status']??null;$class=$fz?strtolower($fz):($finalizeReady?'active':'future');$label=$fz?:($finalizeReady?'Paso activo':'Requiere Admin publish apply OK/WARN');}else{$class=in_array($_SESSION['finalize_apply_status']??null,array('OK','WARN'),true)?'ok':'future';$label=$class==='ok'?'Instalador cerrado':'Requiere Finalize apply OK/WARN';}?><li class="<?=dqs_install_h($class)?>"><span><?=$i+1?></span><div><strong><?=dqs_install_h($step)?></strong><small><?=dqs_install_h($label)?></small></div></li><?php }?></ol>
<section><h2>DB / Preflight</h2><ul class="warnings"><li>Usar solo una DB temporal vacía.</li><li>Preflight no modifica la DB.</li><li>Las credenciales nunca se renderizan.</li></ul><form method="post" autocomplete="off"><input type="hidden" name="action" value="db_preflight"><input type="hidden" name="csrf" value="<?=dqs_install_h($_SESSION['csrf'])?>"><div class="form-grid"><label>Host DB<input name="db_host" required maxlength="255" autocomplete="off"></label><label>Nombre DB<input name="db_name" required maxlength="128" autocomplete="off"></label><label>Usuario DB<input name="db_user" required maxlength="128" autocomplete="off"></label><label>Password DB<input name="db_password" type="password" required maxlength="512" autocomplete="new-password"></label></div><button type="submit">Ejecutar preflight</button></form></section>
<?php dqs_install_render_result('Resultado preflight',$dbResult);?>
<section class="schema-panel"><h2>Schema</h2><?php if(!$schemaReady):?><p class="blocked-copy">Bloqueado: vuelva a DB / Preflight y obtenga OK o WARN.</p><?php else:?><form method="post"><input type="hidden" name="action" value="schema_dry_run"><input type="hidden" name="csrf" value="<?=dqs_install_h($_SESSION['csrf'])?>"><label class="check-label"><input type="checkbox" name="include_default_content" value="1" <?=($_SESSION['schema_include_default_content']??true)?'checked':''?>> Incluir contenido predeterminado</label><button type="submit">Ejecutar dry-run de schema</button></form><?php endif;?></section>
<?php dqs_install_render_result('Schema dry-run',$schemaDry);?>
<?php if($applyReady):?><section class="apply-confirm"><h2>Confirmar Schema apply</h2><p><strong>Esto va a crear tablas y seeds en la DB temporal seleccionada.</strong></p><p class="warnings">DDL puede usar autocommit. Ante un fallo parcial, descarte y recree la DB temporal; el instalador web no intenta rollback.</p><form method="post" autocomplete="off"><input type="hidden" name="action" value="schema_apply"><input type="hidden" name="csrf" value="<?=dqs_install_h($_SESSION['csrf'])?>"><label class="check-label"><input type="checkbox" name="confirm_schema_apply" value="1" required> Confirmo que la DB temporal seleccionada puede modificarse</label><label for="confirmation_phrase">Escriba exactamente <code>INSTALAR SCHEMA</code></label><input id="confirmation_phrase" name="confirmation_phrase" required maxlength="32" autocomplete="off"><button class="danger-action" type="submit">Aplicar schema</button></form></section><?php endif;?>
<?php dqs_install_render_result('Schema apply',$schemaApply);?>
<section class="bootstrap-panel"><h2>Bootstrap</h2><?php if(!$bootstrapReady):?><p class="blocked-copy">Bloqueado: complete Schema apply con estado OK o WARN.</p><?php elseif(in_array($_SESSION['bootstrap_apply_status']??null,array('OK','WARN'),true)):?><p>Bootstrap completado. No se permite repetirlo.</p><?php else:?><form method="post" autocomplete="off"><input type="hidden" name="action" value="bootstrap_dry_run"><input type="hidden" name="csrf" value="<?=dqs_install_h($_SESSION['csrf'])?>"><div class="form-grid"><label>Email admin<input name="admin_email" type="email" required maxlength="254" autocomplete="off"></label><label>Password admin (mínimo 6)<input name="admin_password" type="password" required minlength="6" maxlength="512" autocomplete="new-password"></label><label>Confirmar password<input name="admin_password_confirm" type="password" required minlength="6" maxlength="512" autocomplete="new-password"></label><?php foreach(dqs_install_web_bootstrap_fields()as$name=>$spec):?><label><?=dqs_install_h($spec['label'])?><input name="cliente_<?=dqs_install_h($name)?>" maxlength="<?=dqs_install_h($spec['maxlength'])?>" <?=$spec['required']?'required':''?> autocomplete="off"></label><?php endforeach;?></div><button type="submit">Ejecutar dry-run de bootstrap</button></form><?php endif;?></section>
<?php dqs_install_render_result('Bootstrap dry-run',$bootstrapDry);?>
<?php if($bootstrapApplyReady):?><section class="apply-confirm"><h2>Confirmar Bootstrap apply</h2><p><strong>Esto va a crear el usuario/admin inicial y el cliente en la DB seleccionada. No publica carpeta admin, no crea admin_config y no finaliza la instalación.</strong></p><form method="post" autocomplete="off"><input type="hidden" name="action" value="bootstrap_apply"><input type="hidden" name="csrf" value="<?=dqs_install_h($_SESSION['csrf'])?>"><label class="check-label"><input type="checkbox" name="confirm_bootstrap_apply" value="1" required> Confirmo la creación del bootstrap inicial</label><label for="bootstrap_confirmation_phrase">Escriba exactamente <code>CREAR BOOTSTRAP</code></label><input id="bootstrap_confirmation_phrase" name="bootstrap_confirmation_phrase" required maxlength="32" autocomplete="off"><button class="danger-action" type="submit">Crear bootstrap</button></form></section><?php endif;?>
<?php dqs_install_render_result('Bootstrap apply',$bootstrapApply);?>
<section class="admin-publish-panel"><h2>Admin publish</h2><?php if(!$adminPublishReady):?><p class="blocked-copy">Bloqueado: complete Bootstrap apply con estado OK o WARN.</p><?php elseif(in_array($_SESSION['admin_publish_apply_status']??null,array('OK','WARN'),true)):?><p>Admin publish completado. No se permite repetirlo.</p><?php else:?><p>El template y el destino se resuelven por policy interna. Solo se muestra el slug generado.</p><?php if(isset($_SESSION['admin_publish_slug'])):?><p class="admin-slug">Admin slug: <code><?=dqs_install_h($_SESSION['admin_publish_slug'])?></code></p><?php endif;?><form method="post"><input type="hidden" name="action" value="admin_publish_dry_run"><input type="hidden" name="csrf" value="<?=dqs_install_h($_SESSION['csrf'])?>"><button type="submit">Ejecutar dry-run de Admin publish</button></form><?php endif;?></section>
<?php dqs_install_render_result('Admin publish dry-run',$adminPublishDry);?>
<?php if($adminPublishApplyReady):?><section class="apply-confirm"><h2>Confirmar Admin publish apply</h2><p><strong>Esto va a publicar la carpeta admin nueva y registrar admin_config. No crea install.lock y no finaliza la instalación.</strong></p><p>Admin slug: <code><?=dqs_install_h($_SESSION['admin_publish_slug'])?></code></p><form method="post" autocomplete="off"><input type="hidden" name="action" value="admin_publish_apply"><input type="hidden" name="csrf" value="<?=dqs_install_h($_SESSION['csrf'])?>"><label class="check-label"><input type="checkbox" name="confirm_admin_publish_apply" value="1" required> Confirmo la publicación del admin nuevo</label><label for="admin_publish_confirmation_phrase">Escriba exactamente <code>PUBLICAR ADMIN</code></label><input id="admin_publish_confirmation_phrase" name="admin_publish_confirmation_phrase" required maxlength="32" autocomplete="off"><button class="danger-action" type="submit">Publicar admin</button></form></section><?php endif;?>
<?php dqs_install_render_result('Admin publish apply',$adminPublishApply);?>
<section class="finalize-panel"><h2>Finalize</h2><?php if(!$finalizeReady):?><p class="blocked-copy">Bloqueado: complete Admin publish apply y conserve válidos sus inputs privados.</p><?php else:?><p>Admin slug: <code><?=dqs_install_h($_SESSION['admin_publish_slug'])?></code></p><form method="post"><input type="hidden" name="action" value="finalize_dry_run"><input type="hidden" name="csrf" value="<?=dqs_install_h($_SESSION['csrf'])?>"><button type="submit">Ejecutar dry-run de Finalize</button></form><?php endif;?></section>
<?php dqs_install_render_result('Finalize dry-run',$finalizeDry);?>
<?php if($finalizeApplyReady):?><section class="apply-confirm"><h2>Confirmar Finalize apply</h2><p><strong>Esto va a publicar conexion.php final, crear install.lock y cerrar el instalador. Después de finalizar, /install/ quedará bloqueado.</strong></p><p>Admin slug: <code><?=dqs_install_h($_SESSION['admin_publish_slug'])?></code></p><form method="post" autocomplete="off"><input type="hidden" name="action" value="finalize_apply"><input type="hidden" name="csrf" value="<?=dqs_install_h($_SESSION['csrf'])?>"><label class="check-label"><input type="checkbox" name="confirm_finalize_apply" value="1" required> Confirmo el cierre irreversible del instalador</label><label for="finalize_confirmation_phrase">Escriba exactamente <code>FINALIZAR INSTALACION</code></label><input id="finalize_confirmation_phrase" name="finalize_confirmation_phrase" required maxlength="32" autocomplete="off"><button class="danger-action" type="submit">Finalizar instalación</button></form></section><?php endif;?>
<?php dqs_install_render_result('Finalize apply',$finalizeApply);?>
<section><h2>Controles</h2><ul class="checks"><li>Gate habilitado <b>OK</b></li><li>Sesión autenticada <b>OK</b></li><li>install.lock ausente <b>OK</b></li><li>Finalize <b><?=dqs_install_h($finalizeReady?'Activo':'Bloqueado')?></b></li></ul></section><form method="post"><input type="hidden" name="action" value="logout"><input type="hidden" name="csrf" value="<?=dqs_install_h($_SESSION['csrf'])?>"><button class="secondary" type="submit">Cerrar sesión</button></form><?php endif;?><?php endif;?></main></body></html>
