<?php
include 'conexion.php';



session_start();
if (!isset($_SESSION['usuario_id'])) {
    header('Location: login.php');
    exit;
}


$usuario_id = $_SESSION['usuario_id'];

date_default_timezone_set("America/Argentina/Buenos_Aires");

$hoy = date('d/m/Y H:i:s', strtotime('+21 hours'));
$producto = isset($_GET['producto']) ? $_GET['producto'] : 'Producto Desconocido';
$precio = isset($_GET['precio']) ? number_format($_GET['precio'], 0, ',', '.') : '0';


$sql_usuario = "SELECT nombre FROM usuarios WHERE id = $usuario_id";
$result_usuario = $conn->query($sql_usuario);
$usuario_nombre = "Usuario";

if ($result_usuario && $result_usuario->num_rows > 0) {
    $fila = $result_usuario->fetch_assoc();
    $usuario_nombre = $fila['nombre'];
}

// Frases aleatorias (compatibles con PHP 5.3)
$frases = array(
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena.",
				"Los hermanos sean unidos.",
				"El que nace barrigón, es al ñudo que lo fajen.",
				"Más sabe el diablo por viejo que por diablo.",
				"El que no sabe es como el que no ve.",
				"Nadie sabe en qué rincón se oculta la desgracia.",
				"Es mejor que aprender mucho el aprender cosas buenas.",
				"La ley es tela de araña.",
				"No se hagan los dormidos cuando les llaman la atención.",
				"Aprovecha la ocasión.",
				"Hacete amigo del juez.",
				"El tiempo es un gran maestro.",
				"El que vive de ilusiones muere de desengaños.",
				"Más ruido hace un solo hombre gritando que cien callando.",
				"El que mucho abarca, poco aprieta.",
				"El que quiere a su madre no le hace mal a nadie.",
				"La lengua no tiene hueso, pero corta lo más grueso.",
				"Dios ayuda al que madruga.",
				"Donde hay poca justicia, es un peligro tener razón.",
				"El hombre no ha de ser vago.",
				"Nadie escarmienta en cabeza ajena."
);
$frase_final = $frases[array_rand($frases)];
?>

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Ticket</title>
  <style>
    @page {
      margin: 0;
    }
    @media print {
      body {
        margin: 0;
      }
      .ticket {
        width: 45mm;
        margin: 0 auto;
        box-sizing: border-box;
        padding-bottom: 22mm;
        page-break-inside: avoid;
        break-inside: avoid;
      }
      .ticket::after {
        content: "";
        display: block;
        height: 22mm;
      }
    }
    body {
      font-family: monospace;
      font-size: 12px;
      margin: 0;
      padding: 0;
      background: #fff;
    }
    .ticket {
      width: 45mm;
      padding: 5px;
      margin: auto;
    }
    .centrado {
      text-align: center;
    }
    .linea {
      border-top: 1px dashed #000;
      margin: 10px 0;
    }
    .detalle {
      margin: 5px 0;
    }
    .producto-nombre {
      font-size: 16px;
      font-weight: bold;
      text-align: center;
      margin: 2px 0;
    }
    .frase-final {
      font-style: italic;
      font-size: 11px;
      margin-top: 10px;
    }
  </style>
  <script>
    window.onload = function () {
      window.print();
      setTimeout(function() { window.close(); }, 1000);
    }
  </script>
</head>
<body>
<div class="ticket">
  <p class="centrado" style="font-size:14px; font-weight:bold;">- JINETEADA LAI -</p>
  <p class="centrado">PARA RETIRAR</p>
  <div class="linea"></div>
  <p class="centrado"><?php echo $hoy; ?></p>
<p class="centrado" style="margin-top:10px;">Atendido por: <?php echo $usuario_nombre; ?></p>

  <div class="linea"></div>
  
  <div class="detalle">
    <p class="centrado"><strong>Producto:</strong></p>
    <p class="producto-nombre"><?php echo $producto; ?></p>
  </div>
  
  <div class="linea"></div>
  
  <div class="detalle centrado">
    <span><strong>Precio:</strong> $ <?php echo $precio; ?></span>
  </div>
  
  <div class="linea"></div>
  <p class="centrado frase-final">"<?php echo $frase_final; ?>"</p>
  


</div>
</body>
</html>
